# Development services only - for running One Ring locally
# This starts only the required backend services, not the main app

services:
  mongodb:
    container_name: chat-mongodb-dev
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./appdata/mongodb:/data/db
    command: mongod --noauth

  meilisearch:
    container_name: chat-meilisearch-dev
    image: getmeili/meilisearch:v1.12.3
    restart: unless-stopped
    ports:
      - "7700:7700"
    environment:
      - MEILI_HOST=http://localhost:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-your_master_key_here}
    volumes:
      - ./appdata/meilisearch:/meili_data

  vectordb:
    container_name: vectordb-dev
    image: ankane/pgvector:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./appdata/pgvector:/var/lib/postgresql/data

  rag_api:
    container_name: rag_api-dev
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    restart: unless-stopped
    ports:
      - "${RAG_PORT:-8000}:${RAG_PORT:-8000}"
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    depends_on:
      - vectordb
    env_file:
      - .env